import rateLimit from "express-rate-limit";
const mins = (input) => input * 60 * 1000;
const rateLimiterCache = new Map();

// Match schema on pumpagent.com/fees
const tierSettings = {
  Apprentice: {
    "/": { max: 5000, windowMs: mins(60) },
    "/generate-wallets": { max: 5000, windowMs: mins(60) },
    "/fund-wallets": { max: 5000, windowMs: mins(60) },
    "/claim-profits": { max: 5000, windowMs: mins(60) },
    "/create-ipfs": { max: 100, windowMs: mins(60) },
    "/create-lookup-table": { max: 5000, windowMs: mins(60) },
    "/extend-lookup-table": { max: 5000, windowMs: mins(60) },
    "/pump-chart": { max: 15000, windowMs: mins(60) },
    "/pumpswap-chart": { max: 15000, windowMs: mins(60) },
    "/pump-bonding-curve": { max: 5000, windowMs: mins(60) },
    "/pump-token-bump": { max: 10000, windowMs: mins(60) },
    "/pump-single-buy": { max: 5000, windowMs: mins(60) },
    "/pump-single-sell": { max: 5000, windowMs: mins(60) },
    "/pump-multi-buy": { max: 5000, windowMs: mins(60) },
    "/pump-multi-sell": { max: 5000, windowMs: mins(60) },
    "/pump-dump-all": { max: 5000, windowMs: mins(60) },
    "/pump-launch-token": { max: 5000, windowMs: mins(60) },
    "/pump-launch-bundle": { max: 5000, windowMs: mins(60) },
    "/dex-single-buy": { max: 5000, windowMs: mins(60) },
    "/dex-single-sell": { max: 5000, windowMs: mins(60) },
    "/dex-paid": { max: 5000, windowMs: mins(60) },
    "/landing-info": { max: 5000, windowMs: mins(60) },
    "/dashboard": { max: 5000, windowMs: mins(60) },
    "/signin": { max: 500, windowMs: mins(60) },
    "/create-koltrade-wallet": { max: 100, windowMs: mins(60) },
    "/load-koltrader": { max: 100, windowMs: mins(60) },
    "/sol-balance": { max: 5000, windowMs: mins(60) },
    "/update-koltrade-strategies": { max: 100, windowMs: mins(60) },
    "/koltrader-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-sell": { max: 5000, windowMs: mins(60) },
    "/token-balances": { max: 1000, windowMs: mins(60) },
    "/pump-token-info": { max: 10000, windowMs: mins(60) },
    "/load-openpositions": { max: 1000, windowMs: mins(60) },
    "/comment-thread": { max: 2000, windowMs: mins(60) },
    "/koltrader-bump": { max: 15000, windowMs: mins(60) },
    "/sign-up": { max: 100, windowMs: mins(60) },
    "/get-balance": { max: 1000, windowMs: mins(60) },
    "/pumpswap-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-sell": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-withdraw": { max: 5000, windowMs: mins(60) },
    "/sol-balances": { max: 1000, windowMs: mins(60) },
    "/upload-image": { max: 1000, windowMs: mins(60) },
    "/mint-holders": { max: 1000, windowMs: mins(60) },
    "/get-mint-balances-for-holders": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-buy-transaction": { max: 1000, windowMs: mins(60) },
    "/confirm-transaction": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-sell-transaction": { max: 1000, windowMs: mins(60) },
    "/confirm-bundle": { max: 1000, windowMs: mins(60) },
    "/reclaim-rent": { max: 1000, windowMs: mins(60) },
    "/token-info": { max: 1000, windowMs: mins(60) },
    "/asset-info": { max: 1000, windowMs: mins(60) },
    "/token-bump": { max: 5000, windowMs: mins(60) },
    "/bonk-launch-bundle": { max: 5000, windowMs: mins(60) },
  },
  Alchemist: {
    "/": { max: 1000, windowMs: mins(60) },
    "/generate-wallets": { max: 5000, windowMs: mins(60) },
    "/fund-wallets": { max: 5000, windowMs: mins(60) },
    "/claim-profits": { max: 5000, windowMs: mins(60) },
    "/create-ipfs": { max: 5000, windowMs: mins(60) },
    "/create-lookup-table": { max: 5000, windowMs: mins(60) },
    "/extend-lookup-table": { max: 5000, windowMs: mins(60) },
    "/pump-chart": { max: 15000, windowMs: mins(60) },
    "/pumpswap-chart": { max: 15000, windowMs: mins(60) },
    "/pump-bonding-curve": { max: 5000, windowMs: mins(60) },
    "/pump-token-bump": { max: 20000, windowMs: mins(60) },
    "/pump-single-buy": { max: 5000, windowMs: mins(60) },
    "/pump-single-sell": { max: 5000, windowMs: mins(60) },
    "/pump-multi-buy": { max: 5000, windowMs: mins(60) },
    "/pump-multi-sell": { max: 5000, windowMs: mins(60) },
    "/pump-dump-all": { max: 5000, windowMs: mins(60) },
    "/pump-launch-token": { max: 5000, windowMs: mins(60) },
    "/pump-launch-bundle": { max: 5000, windowMs: mins(60) },
    "/dex-single-buy": { max: 5000, windowMs: mins(60) },
    "/dex-single-sell": { max: 5000, windowMs: mins(60) },
    "/dex-paid": { max: 5000, windowMs: mins(60) },
    "/landing-info": { max: 1000, windowMs: mins(60) },
    "/dashboard": { max: 1000, windowMs: mins(60) },
    "/signin": { max: 500, windowMs: mins(60) },
    "/create-koltrade-wallet": { max: 100, windowMs: mins(60) },
    "/load-koltrader": { max: 100, windowMs: mins(60) },
    "/sol-balance": { max: 5000, windowMs: mins(60) },
    "/update-koltrade-strategies": { max: 100, windowMs: mins(60) },
    "/koltrader-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-sell": { max: 5000, windowMs: mins(60) },
    "/token-balances": { max: 5000, windowMs: mins(60) },
    "/pump-token-info": { max: 10000, windowMs: mins(60) },
    "/load-openpositions": { max: 5000, windowMs: mins(60) },
    "/comment-thread": { max: 5000, windowMs: mins(60) },
    "/koltrader-bump": { max: 15000, windowMs: mins(60) },
    "/sign-up": { max: 100, windowMs: mins(60) },
    "/get-balance": { max: 1000, windowMs: mins(60) },
    "/pumpswap-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-sell": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-withdraw": { max: 5000, windowMs: mins(60) },
    "/sol-balances": { max: 1000, windowMs: mins(60) },
    "/upload-image": { max: 1000, windowMs: mins(60) },
    "/mint-holders": { max: 1000, windowMs: mins(60) },
    "/get-mint-balances-for-holders": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-buy-transaction": { max: 1000, windowMs: mins(60) },
    "/confirm-transaction": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-sell-transaction": { max: 1000, windowMs: mins(60) },
    "/reclaim-rent": { max: 1000, windowMs: mins(60) },
    "/reclaim-sol": { max: 1000, windowMs: mins(60) },
    "/confirm-bundle": { max: 1000, windowMs: mins(60) },
    "/token-info": { max: 5000, windowMs: mins(60) },
    "/asset-info": { max: 1000, windowMs: mins(60) },
    "/token-bump": { max: 5000, windowMs: mins(60) },
    "/bonk-launch-bundle": { max: 5000, windowMs: mins(60) },
  },
  God: {
    "/": { max: 1000, windowMs: mins(60) },
    "/generate-wallets": { max: 5000, windowMs: mins(60) },
    "/fund-wallets": { max: 5000, windowMs: mins(60) },
    "/claim-profits": { max: 5000, windowMs: mins(60) },
    "/create-ipfs": { max: 5000, windowMs: mins(60) },
    "/create-lookup-table": { max: 5000, windowMs: mins(60) },
    "/extend-lookup-table": { max: 5000, windowMs: mins(60) },
    "/pump-chart": { max: 15000, windowMs: mins(60) },
    "/pumpswap-chart": { max: 15000, windowMs: mins(60) },
    "/pump-bonding-curve": { max: 5000, windowMs: mins(60) },
    "/pump-token-bump": { max: 20000, windowMs: mins(60) },
    "/pump-single-buy": { max: 5000, windowMs: mins(60) },
    "/pump-single-sell": { max: 5000, windowMs: mins(60) },
    "/pump-multi-buy": { max: 5000, windowMs: mins(60) },
    "/pump-multi-sell": { max: 5000, windowMs: mins(60) },
    "/pump-dump-all": { max: 5000, windowMs: mins(60) },
    "/pump-launch-token": { max: 5000, windowMs: mins(60) },
    "/pump-launch-bundle": { max: 5000, windowMs: mins(60) },
    "/dex-single-buy": { max: 5000, windowMs: mins(60) },
    "/dex-single-sell": { max: 5000, windowMs: mins(60) },
    "/dex-paid": { max: 5000, windowMs: mins(60) },
    "/landing-info": { max: 1000, windowMs: mins(60) },
    "/dashboard": { max: 1000, windowMs: mins(60) },
    "/signin": { max: 500, windowMs: mins(60) },
    "/create-koltrade-wallet": { max: 100, windowMs: mins(60) },
    "/load-koltrader": { max: 100, windowMs: mins(60) },
    "/sol-balance": { max: 5000, windowMs: mins(60) },
    "/update-koltrade-strategies": { max: 100, windowMs: mins(60) },
    "/koltrader-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-sell": { max: 5000, windowMs: mins(60) },
    "/token-balances": { max: 5000, windowMs: mins(60) },
    "/pump-token-info": { max: 10000, windowMs: mins(60) },
    "/load-openpositions": { max: 5000, windowMs: mins(60) },
    "/comment-thread": { max: 5000, windowMs: mins(60) },
    "/koltrader-bump": { max: 15000, windowMs: mins(60) },
    "/sign-up": { max: 100, windowMs: mins(60) },
    "/get-balance": { max: 1000, windowMs: mins(60) },
    "/pumpswap-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-sell": { max: 5000, windowMs: mins(60) },
    "/koltrader-dex-buy": { max: 5000, windowMs: mins(60) },
    "/koltrader-withdraw": { max: 5000, windowMs: mins(60) },
    "/sol-balances": { max: 1000, windowMs: mins(60) },
    "/upload-image": { max: 1000, windowMs: mins(60) },
    "/mint-holders": { max: 1000, windowMs: mins(60) },
    "/get-mint-balances-for-holders": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-buy-transaction": { max: 1000, windowMs: mins(60) },
    "/confirm-transaction": { max: 1000, windowMs: mins(60) },
    "/create-pumpfun-sell-transaction": { max: 1000, windowMs: mins(60) },
    "/reclaim-rent": { max: 1000, windowMs: mins(60) },
    "/reclaim-sol": { max: 1000, windowMs: mins(60) },
    "/confirm-bundle": { max: 1000, windowMs: mins(60) },
    "/token-info": { max: 5000, windowMs: mins(60) },
    "/asset-info": { max: 1000, windowMs: mins(60) },
    "/token-bump": { max: 5000, windowMs: mins(60) },
    "/bonk-launch-bundle": { max: 5000, windowMs: mins(60) },
  },
};

export function reqLimit() {
  return (req, res, next) => {
    const tier = req.tier || "Apprentice"; // set by checkApiKey
    const path = req.originalUrl || "/";
    const tierConfig = tierSettings[tier];
    const settings = tierConfig?.[path];

    if (!settings) {
      // If path is not rate-limited for the tier, allow through
      console.warn(`No rate limit config for ${path} under tier ${tier}`);
      return next();
    }

    const key = `${tier}:${path}`;

    if (!rateLimiterCache.has(key)) {
      rateLimiterCache.set(
        key,
        rateLimit({
          windowMs: settings.windowMs,
          max: settings.max,
          standardHeaders: true,
          legacyHeaders: false,
          keyGenerator: (req) => req.apiKey || req.ip,
        })
      );
    }

    const limiter = rateLimiterCache.get(key);
    return limiter(req, res, next);
  };
}
